{% set name = "fatpack" %}
{% set version = "0.7.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fatpack-{{ version }}.tar.gz
  sha256: afb0804844f98672e839764bae490e20a30eadcae693ec86731258001ac7f5e9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - fatpack
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gunnstein/fatpack
  summary: Fatigue analysis in python
  description: |
    The package provides classes and functions for rainflow cycle counting,
    defining endurance curves, mean and compressive stress range correction
    and racetrack filtering. The code example below shows how fatigue damage
    can be calculated.
  license: ISC
  license_file: LICENSE
  dev_url: https://github.com/gunnstein/fatpack

extra:
  recipe-maintainers:
    - gunnstein
    - gbarter
