{% set name = "fatpack" %}
{% set version = "0.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fatpack-{{ version }}.tar.gz
  sha256: 30d8679f5f91c54879da1058357b72ceb1f8b025410eb14fcb3cc69a17299659

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - fatpack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gunnstein/fatpack
  summary: Fatigue analysis in python
  description: |
    The package provides classes and functions for rainflow cycle counting,
    defining endurance curves, mean and compressive stress range correction
    and racetrack filtering. The code example below shows how fatigue damage
    can be calculated.
  license: ISC
  license_file: LICENSE
  dev_url: https://github.com/gunnstein/fatpack

extra:
  recipe-maintainers:
    - gunnstein
    - gbarter
