{% set name = "fatpack" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fatpack-{{ version }}.tar.gz
  sha256: d152af7dd82a0d482935a385e362f8a9d1509e78cd12317d7bbe0383ea1b3c58

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - fatpack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gunnstein/fatpack
  summary: "Fatigue analysis in python"
  description: |
      The package provides classes and functions for rainflow cycle counting,
      defining endurance curves, mean and compressive stress range correction
      and racetrack filtering. The code example below shows how fatigue damage
      can be calculated.
  license: ISC
  license_file: LICENSE
  dev_url: https://github.com/gunnstein/fatpack

extra:
  recipe-maintainers:
    - gunnstein
    - gbarter
